version: '3'

services:
  stake_checker_bot:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/app
    depends_on:
      db:
          condition: service_healthy
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stch_user -d stake_checker_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - stake_checker_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: stch_user
      POSTGRES_DB: stake_checker_db
      POSTGRES_PASSWORD: stchuserpassword
    ports:
      - "5432:5432"

volumes:
  stake_checker_pg_data:
